### ISSUE TITLE
No need to override setMessage() and getMessage()

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-PittayutSothanakul#4]
Your game doesn't have to override messages methods. You can use the methods and attributes from the superclass.

**Comment by PittayutSothanakul** [comment]
I remove Override already.

**Comment by bokherus** [comment]
You can use the methods and attributes from the superclass. There's no need to write the method in your game.

**Comment by PittayutSothanakul** [comment]
I delete setMessage() and getMessage() already.
