### ISSUE TITLE
GameSolver shouldn't print anything

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-PittayutSothanakul#5]
Please return only the solution.

As specified in the labsheet
https://skeoop.github.io/week1/Lab1-Guessing-Game.pdf

**Comment by PittayutSothanakul** [comment]
I remove print in Gamsolver already.

**Comment by bokherus** [comment]
You're still printing something like 
**time 1
Your answer? 5
too large
time 2
Your answer? 3**

**Comment by PittayutSothanakul** [comment]
I print like
**time 1
Your answer? 5
too large
time 2
Your answer? 3**
already
